// <auto-generated />
using System;
using MangaT.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaT.Infrastructure.Migrations
{
    [DbContext(typeof(MangaDbContext))]
    [Migration("20260611030140_InicializacionDb")]
    partial class InicializacionDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MangaT.Domain.Entities.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DetailUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Point")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("VolumeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mangas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Eiichiro Oda",
                            Category = "Adventure",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A story about a group of pirates searching for the ultimate treasure.",
                            DetailUrl = "https://example.com/onepiece",
                            ImageUrl = "https://example.com/onepiece.jpg",
                            Point = 9.5,
                            Title = "One Piece",
                            VolumeCount = 100
                        },
                        new
                        {
                            Id = 2,
                            Author = "Masashi Kishimoto",
                            Category = "Action",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A young ninja's journey to become the strongest in his village.",
                            DetailUrl = "https://example.com/naruto",
                            ImageUrl = "https://example.com/naruto.jpg",
                            Point = 9.0,
                            Title = "Naruto",
                            VolumeCount = 72
                        },
                        new
                        {
                            Id = 3,
                            Author = "Tite Kubo",
                            Category = "Fantasy",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A teenager gains the powers of a Soul Reaper and battles evil spirits.",
                            DetailUrl = "https://example.com/bleach",
                            ImageUrl = "https://example.com/bleach.jpg",
                            Point = 8.5,
                            Title = "Bleach",
                            VolumeCount = 74
                        },
                        new
                        {
                            Id = 4,
                            Author = "Hajime Isayama",
                            Category = "Horror",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Humanity's fight for survival against giant humanoid creatures.",
                            DetailUrl = "https://example.com/attackontitan",
                            ImageUrl = "https://example.com/attackontitan.jpg",
                            Point = 9.8000000000000007,
                            Title = "Attack on Titan",
                            VolumeCount = 34
                        },
                        new
                        {
                            Id = 5,
                            Author = "Kohei Horikoshi",
                            Category = "Superhero",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "In a world where superpowers are the norm, a boy without them strives to be a hero.",
                            DetailUrl = "https://example.com/myheroacademia",
                            ImageUrl = "https://example.com/myheroacademia.jpg",
                            Point = 9.1999999999999993,
                            Title = "My Hero Academia",
                            VolumeCount = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
